//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int ChildID { get; set; }
        public int FamilyID { get; set; }
        public string ChildName { get; set; }
        public string ChildTZ { get; set; }
        public Nullable<System.TimeSpan> DateOfBirth { get; set; }
        public string Class { get; set; }
        public string Clinic { get; set; }
        public string Comments { get; set; }
    }
}
