//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int CreditCardID { get; set; }
        public int PaymentAccountsID { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.TimeSpan> Validity { get; set; }
        public Nullable<int> SecurityIterature { get; set; }
        public string NameCardHolder { get; set; }
        public string TZCardHolder { get; set; }
    }
}
