//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        public int FamilyID { get; set; }
        public string LastName { get; set; }
        public string Adress { get; set; }
        public string Phon { get; set; }
        public string FatherName { get; set; }
        public string FatherTZ { get; set; }
        public string FatherCellPhon { get; set; }
        public string MotherName { get; set; }
        public string MotherID { get; set; }
        public string MotherCellPhon { get; set; }
        public string Comments { get; set; }
    }
}
