//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentAccount
    {
        public int PaymentAccountsID { get; set; }
        public int FamilyID { get; set; }
        public Nullable<short> PeymentType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
